[2024-12-29T00:03:36.334+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:03:36.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:03:36.363+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:03:36.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:03:36.425+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:03:36.421+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:03:36.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:03:36.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.590 seconds
[2024-12-29T00:04:07.737+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:04:07.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:04:07.742+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:04:07.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:04:07.750+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:04:07.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:04:07.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:04:07.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.052 seconds
[2024-12-29T00:04:37.875+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:04:37.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:04:37.880+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:04:37.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:04:37.888+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:04:37.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:04:37.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:04:37.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.045 seconds
[2024-12-29T00:05:08.290+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:05:08.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:05:08.295+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:05:08.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:05:08.305+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:05:08.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:05:08.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:05:08.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.057 seconds
[2024-12-29T00:05:38.396+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:05:38.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:05:38.401+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:05:38.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:05:38.406+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:05:38.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:05:38.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:05:38.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.050 seconds
[2024-12-29T00:06:08.497+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:06:08.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:06:08.501+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:06:08.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:06:08.510+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:06:08.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:06:08.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:06:08.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.049 seconds
[2024-12-29T00:06:39.179+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:06:39.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:06:39.184+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:06:39.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:06:39.190+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:06:39.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:06:39.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:06:39.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.041 seconds
[2024-12-29T00:07:10.151+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:07:10.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:07:10.156+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:07:10.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:07:10.162+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:07:10.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:07:10.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:07:10.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.043 seconds
[2024-12-29T00:07:40.385+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:07:40.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:07:40.390+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:07:40.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:07:40.400+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:07:40.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:07:40.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:07:40.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.057 seconds
[2024-12-29T00:08:11.367+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:08:11.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:08:11.372+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:08:11.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:08:11.377+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:08:11.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:08:11.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:08:11.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.044 seconds
[2024-12-29T00:08:41.671+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:08:41.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:08:41.677+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:08:41.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:08:41.685+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:08:41.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:08:41.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:08:41.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.058 seconds
[2024-12-29T00:09:12.379+0000] {processor.py:186} INFO - Started process (PID=754) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:09:12.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:09:12.383+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:09:12.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:09:12.387+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:09:12.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:09:12.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:09:12.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.036 seconds
[2024-12-29T00:09:42.629+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:09:42.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:09:42.633+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:09:42.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:09:42.638+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:09:42.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:09:42.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:09:42.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.040 seconds
[2024-12-29T00:10:13.004+0000] {processor.py:186} INFO - Started process (PID=882) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:10:13.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:10:13.009+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:10:13.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:10:13.018+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:10:13.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:10:13.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:10:13.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.051 seconds
[2024-12-29T00:10:43.153+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:10:43.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:10:43.159+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:10:43.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:10:43.168+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:10:43.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:10:43.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:10:43.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.051 seconds
[2024-12-29T00:11:13.690+0000] {processor.py:186} INFO - Started process (PID=1016) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:11:13.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:11:13.698+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:11:13.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:11:13.702+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:11:13.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:11:13.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:11:13.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.045 seconds
[2024-12-29T00:11:43.832+0000] {processor.py:186} INFO - Started process (PID=1080) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:11:43.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:11:43.837+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:11:43.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:11:43.846+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:11:43.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:11:43.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:11:43.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.054 seconds
[2024-12-29T00:12:14.373+0000] {processor.py:186} INFO - Started process (PID=1144) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:12:14.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:12:14.379+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:12:14.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:12:14.388+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:12:14.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:12:14.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:12:14.421+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.055 seconds
[2024-12-29T00:12:45.336+0000] {processor.py:186} INFO - Started process (PID=1208) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:12:45.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:12:45.340+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:12:45.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:12:45.345+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:12:45.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:12:45.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:12:45.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.039 seconds
[2024-12-29T00:13:19.360+0000] {processor.py:186} INFO - Started process (PID=1265) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:13:19.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:13:19.767+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:13:19.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:13:19.840+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:13:19.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
ModuleNotFoundError: No module named 'scripts.daily_news_etl'
[2024-12-29T00:13:19.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:13:19.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.612 seconds
[2024-12-29T00:13:50.168+0000] {processor.py:186} INFO - Started process (PID=1329) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:13:50.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:13:50.173+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:13:50.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:13:50.181+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:13:50.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:13:50.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:13:50.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.052 seconds
[2024-12-29T00:14:20.870+0000] {processor.py:186} INFO - Started process (PID=1392) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:14:20.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:14:20.875+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:14:20.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:14:20.882+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:14:20.881+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:14:20.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:14:20.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.045 seconds
[2024-12-29T00:14:51.191+0000] {processor.py:186} INFO - Started process (PID=1457) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:14:51.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:14:51.196+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:14:51.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:14:51.202+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:14:51.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:14:51.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:14:51.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.048 seconds
[2024-12-29T00:15:21.401+0000] {processor.py:186} INFO - Started process (PID=1522) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:15:21.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:15:21.408+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:15:21.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:15:21.419+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:15:21.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:15:21.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:15:21.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.059 seconds
[2024-12-29T00:15:52.335+0000] {processor.py:186} INFO - Started process (PID=1587) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:15:52.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:15:52.352+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:15:52.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:15:52.376+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:15:52.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:15:52.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:15:52.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.115 seconds
[2024-12-29T00:16:22.678+0000] {processor.py:186} INFO - Started process (PID=1652) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:16:22.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:16:22.683+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:16:22.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:16:22.694+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:16:22.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:16:22.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:16:22.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.055 seconds
[2024-12-29T00:16:53.222+0000] {processor.py:186} INFO - Started process (PID=1717) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:16:53.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:16:53.227+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:16:53.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:16:53.239+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:16:53.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:16:53.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:16:53.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.053 seconds
[2024-12-29T00:19:50.332+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:19:50.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:19:50.373+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:19:50.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:19:50.395+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:19:50.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:19:50.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:19:50.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.152 seconds
[2024-12-29T00:20:21.043+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:20:21.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:20:21.047+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:20:21.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:20:21.054+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:20:21.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:20:21.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:20:21.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.046 seconds
[2024-12-29T00:20:51.278+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:20:51.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:20:51.284+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:20:51.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:20:51.290+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:20:51.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:20:51.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:20:51.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.046 seconds
[2024-12-29T00:21:22.018+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:21:22.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:21:22.023+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:21:22.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:21:22.028+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:21:22.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:21:22.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:21:22.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.042 seconds
[2024-12-29T00:21:52.249+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:21:52.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:21:52.253+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:21:52.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:21:52.260+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:21:52.258+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:21:52.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:21:52.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.051 seconds
[2024-12-29T00:22:23.057+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:22:23.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:22:23.061+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:22:23.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:22:23.065+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:22:23.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:22:23.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:22:23.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.037 seconds
[2024-12-29T00:22:53.604+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:22:53.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:22:53.611+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:22:53.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:22:53.618+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:22:53.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:22:53.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:22:53.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.066 seconds
[2024-12-29T00:23:23.926+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:23:23.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:23:23.930+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:23:23.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:23:23.936+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:23:23.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:23:23.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:23:23.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.049 seconds
[2024-12-29T00:23:54.285+0000] {processor.py:186} INFO - Started process (PID=603) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:23:54.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:23:54.289+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:23:54.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:23:54.293+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:23:54.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:23:54.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:23:54.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.038 seconds
[2024-12-29T00:24:24.792+0000] {processor.py:186} INFO - Started process (PID=668) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:24:24.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:24:24.798+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:24:24.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:24:24.805+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:24:24.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:24:24.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:24:24.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.056 seconds
[2024-12-29T00:24:55.076+0000] {processor.py:186} INFO - Started process (PID=733) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:24:55.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:24:55.081+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:24:55.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:24:55.086+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:24:55.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:24:55.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:24:55.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.045 seconds
[2024-12-29T00:25:25.378+0000] {processor.py:186} INFO - Started process (PID=798) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:25:25.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:25:25.384+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:25:25.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:25:25.389+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:25:25.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:25:25.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:25:25.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.047 seconds
[2024-12-29T00:25:55.590+0000] {processor.py:186} INFO - Started process (PID=863) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:25:55.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:25:55.595+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:25:55.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:25:55.600+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:25:55.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:25:55.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:25:55.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.043 seconds
[2024-12-29T00:26:25.735+0000] {processor.py:186} INFO - Started process (PID=928) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:26:25.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:26:25.739+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:26:25.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:26:25.744+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:26:25.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:26:25.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:26:25.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.041 seconds
[2024-12-29T00:26:56.190+0000] {processor.py:186} INFO - Started process (PID=993) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:26:56.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:26:56.196+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:26:56.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:26:56.201+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:26:56.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:26:56.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:26:56.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.046 seconds
[2024-12-29T00:27:26.439+0000] {processor.py:186} INFO - Started process (PID=1058) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:27:26.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:27:26.444+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:27:26.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:27:26.449+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:27:26.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:27:26.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:27:26.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.045 seconds
[2024-12-29T00:27:56.898+0000] {processor.py:186} INFO - Started process (PID=1123) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:27:56.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:27:56.904+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:27:56.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:27:56.910+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:27:56.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:27:56.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:27:56.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.054 seconds
[2024-12-29T00:28:27.681+0000] {processor.py:186} INFO - Started process (PID=1188) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:28:27.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:28:27.684+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:28:27.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:28:27.689+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:28:27.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:28:27.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:28:27.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.038 seconds
[2024-12-29T00:28:57.912+0000] {processor.py:186} INFO - Started process (PID=1253) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:28:57.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:28:57.916+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:28:57.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:28:57.922+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:28:57.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:28:57.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:28:57.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.044 seconds
[2024-12-29T00:29:28.577+0000] {processor.py:186} INFO - Started process (PID=1318) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:29:28.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:29:28.582+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:29:28.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:29:28.587+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:29:28.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:29:28.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:29:28.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.049 seconds
[2024-12-29T00:29:59.357+0000] {processor.py:186} INFO - Started process (PID=1382) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:29:59.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:29:59.362+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:29:59.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:29:59.368+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:29:59.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:29:59.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:29:59.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.052 seconds
[2024-12-29T00:30:30.175+0000] {processor.py:186} INFO - Started process (PID=1447) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:30:30.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:30:30.181+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:30:30.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:30:30.187+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:30:30.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:30:30.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:30:30.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.048 seconds
[2024-12-29T00:31:01.049+0000] {processor.py:186} INFO - Started process (PID=1496) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:31:01.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:31:01.058+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:31:01.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:31:01.064+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:31:01.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:31:01.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:31:01.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.059 seconds
[2024-12-29T00:31:31.936+0000] {processor.py:186} INFO - Started process (PID=1559) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:31:31.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:31:31.941+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:31:31.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:31:31.948+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:31:31.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:31:31.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:31:31.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.054 seconds
[2024-12-29T00:32:02.967+0000] {processor.py:186} INFO - Started process (PID=1623) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:32:02.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:32:02.972+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:32:02.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:32:02.978+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:32:02.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:32:02.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:32:03.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.048 seconds
[2024-12-29T00:32:33.457+0000] {processor.py:186} INFO - Started process (PID=1683) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:32:33.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:32:33.462+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:32:33.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:32:33.467+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:32:33.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:32:33.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:32:33.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.043 seconds
[2024-12-29T00:33:04.360+0000] {processor.py:186} INFO - Started process (PID=1748) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:33:04.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:33:04.365+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:33:04.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:33:04.370+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:33:04.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:33:04.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:33:04.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.053 seconds
[2024-12-29T00:33:35.220+0000] {processor.py:186} INFO - Started process (PID=1813) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:33:35.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:33:35.226+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:33:35.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:33:35.235+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:33:35.232+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:33:35.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:33:35.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.057 seconds
[2024-12-29T00:34:05.658+0000] {processor.py:186} INFO - Started process (PID=1875) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:34:05.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:34:05.664+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:34:05.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:34:05.671+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:34:05.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:34:05.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:34:05.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.049 seconds
[2024-12-29T00:34:36.616+0000] {processor.py:186} INFO - Started process (PID=1940) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:34:36.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:34:36.625+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:34:36.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:34:36.635+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:34:36.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:34:36.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:34:36.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.071 seconds
[2024-12-29T00:35:07.128+0000] {processor.py:186} INFO - Started process (PID=2005) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:35:07.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:35:07.131+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:35:07.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:35:07.135+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:35:07.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:35:07.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:35:07.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.041 seconds
[2024-12-29T00:35:37.405+0000] {processor.py:186} INFO - Started process (PID=2070) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:35:37.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:35:37.410+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:35:37.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:35:37.414+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:35:37.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:35:37.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:35:37.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.039 seconds
[2024-12-29T00:36:08.220+0000] {processor.py:186} INFO - Started process (PID=2135) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:36:08.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:36:08.225+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:36:08.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:36:08.229+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:36:08.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:36:08.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:36:08.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.042 seconds
[2024-12-29T00:36:38.600+0000] {processor.py:186} INFO - Started process (PID=2200) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:36:38.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:36:38.604+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:36:38.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:36:38.608+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:36:38.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:36:38.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:36:38.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.039 seconds
[2024-12-29T00:37:08.733+0000] {processor.py:186} INFO - Started process (PID=2266) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:37:08.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:37:08.738+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:37:08.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:37:08.743+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:37:08.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:37:08.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:37:08.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.042 seconds
[2024-12-29T00:37:39.020+0000] {processor.py:186} INFO - Started process (PID=2331) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:37:39.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:37:39.033+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:37:39.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:37:39.038+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:37:39.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:37:39.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:37:39.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.058 seconds
[2024-12-29T00:38:09.772+0000] {processor.py:186} INFO - Started process (PID=2396) to work on /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:38:09.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/daily_news_dag.py for tasks to queue
[2024-12-29T00:38:09.777+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:38:09.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:38:09.783+0000] {logging_mixin.py:190} INFO - [2024-12-29T00:38:09.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/daily_news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/daily_news_dag.py", line 5, in <module>
    from scripts.daily_news_etl import main
  File "/opt/airflow/dags/scripts/daily_news_etl.py", line 2, in <module>
    from newsdataapi import NewsDataApiClient
ModuleNotFoundError: No module named 'newsdataapi'
[2024-12-29T00:38:09.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/daily_news_dag.py
[2024-12-29T00:38:09.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/daily_news_dag.py took 0.050 seconds
